#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_accueil_helloWorld:
  path: /hello-world
  controller: App\Controller\AccueilController::helloWorld

app_accueil:
  path: /
  controller: App\Controller\AccueilController::index